<a href="https://colab.research.google.com/github/furqatnizomov/aviachipta-narxi-bashorati/blob/main/aviachipta_narxini_aniqlash.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import pandas as pd
import numpy as np

In [4]:
!unzip /content/aviachipta-narxini-bashorat-qilish.zip

Archive:  /content/aviachipta-narxini-bashorat-qilish.zip
  inflating: sample_solution.csv     
  inflating: test_data.csv           
  inflating: train_data.csv          


In [6]:
train_data = pd.read_csv("/content/train_data.csv")
train_data.head()

id   airline   flight source_city departure_time stops arrival_time  \
0   1   Vistara   UK-810   Bangalore  Early_Morning   one        Night   
1   2  SpiceJet  SG-5094   Hyderabad        Evening  zero        Night   
2   3   Vistara   UK-846   Bangalore        Morning   one      Evening   
3   4   Vistara   UK-706     Kolkata        Morning   one      Evening   
4   5    Indigo  6E-5394     Chennai  Early_Morning  zero      Morning   

  destination_city     class  duration  days_left  price  
0           Mumbai   Economy     14.25         21   7212  
1          Kolkata   Economy      1.75          7   5292  
2            Delhi  Business      9.58          5  60553  
3        Hyderabad   Economy      6.75         28   5760  
4           Mumbai   Economy      2.00          4  10712

In [7]:
sample_data = pd.read_csv("/content/sample_solution.csv")
sample_data

id  price
0        1      0
1        2      0
2        3      0
3        4      0
4        5      0
...    ...    ...
4995  4996      0
4996  4997      0
4997  4998      0
4998  4999      0
4999  5000      0

[5000 rows x 2 columns]

In [8]:
test_data = pd.read_csv("/content/test_data.csv")
test_data

id    airline   flight source_city departure_time stops  \
0        1  Air_India   AI-765     Kolkata        Evening   one   
1        2    Vistara   UK-747       Delhi  Early_Morning   one   
2        3  Air_India   AI-570      Mumbai  Early_Morning  zero   
3        4    AirAsia   I5-974   Hyderabad          Night   one   
4        5  Air_India   AI-770     Kolkata          Night   one   
...    ...        ...      ...         ...            ...   ...   
4995  4996  Air_India   AI-768     Kolkata      Afternoon   one   
4996  4997     Indigo  6E-6214     Kolkata        Morning  zero   
4997  4998  Air_India   AI-402     Kolkata        Morning   one   
4998  4999  Air_India   AI-673      Mumbai  Early_Morning   one   
4999  5000    Vistara   UK-774     Kolkata          Night   one   

       arrival_time destination_city     class  duration  days_left  
0             Night            Delhi  Business     28.25          2  
1             Night           Mumbai  Business     13.83         34  
2     Early_Morning          Chennai  Business      2.00         30  
3        Late_Night            Delhi   Economy      5.17         26  
4         Afternoon           Mumbai   Economy     16.33         35  
...             ...              ...       ...       ...        ...  
4995        Morning        Bangalore  Business     17.42         15  
4996      Afternoon           Mumbai   Economy      3.00         40  
4997          Night           Mumbai  Business     11.17         37  
4998          Night        Hyderabad  Business     13.33         38  
4999      Afternoon            Delhi  Business     16.08         49  

[5000 rows x 11 columns]

# train_datani tayyorlaymiz

In [9]:
train_data['departure_time'].value_counts()

Morning          4738
Early_Morning    4432
Evening          4341
Night            3231
Afternoon        3166
Late_Night         92
Name: departure_time, dtype: int64

In [10]:
train_data['departure_time'].replace("Early_Morning", 0, inplace=True)
train_data['departure_time'].replace("Morning", 1, inplace=True)
train_data['departure_time'].replace("Afternoon", 2, inplace=True)
train_data['departure_time'].replace("Evening", 3, inplace=True)
train_data['departure_time'].replace("Night", 4, inplace=True)
train_data['departure_time'].replace("Late_Night", 5, inplace=True)

In [11]:
train_data['stops'].value_counts()

one            16666
zero            2440
two_or_more      894
Name: stops, dtype: int64

In [12]:
train_data['stops'].replace("one", 1, inplace=True)
train_data['stops'].replace("zero", 0, inplace=True)
train_data['stops'].replace("two_or_more", 2, inplace=True)

In [13]:
train_data['arrival_time'].value_counts()

Night            6142
Evening          5316
Morning          4086
Afternoon        2536
Early_Morning    1004
Late_Night        916
Name: arrival_time, dtype: int64

In [14]:
train_data['arrival_time'].replace("Early_Morning", 0, inplace=True)
train_data['arrival_time'].replace("Morning", 1, inplace=True)
train_data['arrival_time'].replace("Afternoon", 2, inplace=True)
train_data['arrival_time'].replace("Evening", 3, inplace=True)
train_data['arrival_time'].replace("Night", 4, inplace=True)
train_data['arrival_time'].replace("Late_Night", 5, inplace=True)

In [15]:
train_data['class'].value_counts()

Economy     13753
Business     6247
Name: class, dtype: int64

In [16]:
train_data['class'].replace("Economy", 0, inplace=True)
train_data['class'].replace("Business", 1, inplace=True)

In [17]:
train_data.corrwith(train_data['price']).sort_values()

days_left        -0.102545
arrival_time     -0.005670
id               -0.002443
departure_time    0.027532
stops             0.121455
duration          0.213158
class             0.937868
price             1.000000
dtype: float64

In [54]:
X_train = train_data[['duration','class','stops','days_left']]
y_train = train_data['price']

In [55]:
X_train

duration  class  stops  days_left
0         14.25      0      1         21
1          1.75      0      0          7
2          9.58      1      1          5
3          6.75      0      1         28
4          2.00      0      0          4
...         ...    ...    ...        ...
19995      7.92      0      1         45
19996      5.83      0      1         24
19997     35.33      0      2         17
19998     16.33      0      1         21
19999     18.25      0      1         26

[20000 rows x 4 columns]

In [56]:
y_train

0         7212
1         5292
2        60553
3         5760
4        10712
         ...  
19995     3153
19996     3911
19997    14822
19998     6450
19999     7141
Name: price, Length: 20000, dtype: int64

# test_datani tayyorlaymiz

In [57]:
test_data['class'].value_counts()

0    3473
1    1527
Name: class, dtype: int64

In [58]:
test_data['class'].replace("Economy", 0, inplace=True)
test_data['class'].replace("Business", 1, inplace=True)

In [59]:
test_data['stops'].replace("one", 1, inplace=True)
test_data['stops'].replace("zero", 0, inplace=True)
test_data['stops'].replace("two_or_more", 2, inplace=True)

In [60]:
X_test = test_data[['duration','class','stops','days_left']]
X_test

duration  class  stops  days_left
0        28.25      1      1          2
1        13.83      1      1         34
2         2.00      1      0         30
3         5.17      0      1         26
4        16.33      0      1         35
...        ...    ...    ...        ...
4995     17.42      1      1         15
4996      3.00      0      0         40
4997     11.17      1      1         37
4998     13.33      1      1         38
4999     16.08      1      1         49

[5000 rows x 4 columns]

# Standardlash

In [61]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_train_scaled

array([[ 0.28952803, -0.67396452,  0.19281382, -0.36141789],
       [-1.45682723, -0.67396452, -2.30154354, -1.38897606],
       [-0.36291029,  1.48375764,  0.19281382, -1.53577008],
       ...,
       [ 3.23458153, -0.67396452,  2.68717119, -0.65500594],
       [ 0.58012154, -0.67396452,  0.19281382, -0.36141789],
       [ 0.84836171, -0.67396452,  0.19281382,  0.00556716]])

In [62]:
X_test_scaled = scaler.fit_transform(X_test)
X_test_scaled

array([[ 2.17930407,  1.50810949,  0.20037687, -1.75411081],
       [ 0.20548051,  1.50810949,  0.20037687,  0.58318436],
       [-1.41382134,  1.50810949, -2.38179933,  0.29102246],
       ...,
       [-0.15862287,  1.50810949,  0.20037687,  0.80230578],
       [ 0.13704002,  1.50810949,  0.20037687,  0.87534626],
       [ 0.51346269,  1.50810949,  0.20037687,  1.67879147]])

# Training

In [63]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train_scaled, y_train)

LinearRegression()

In [64]:
result_of_test = model.predict(X_test_scaled)
result_of_test

array([57963.97601777, 52527.67348073, 45657.33670231, ...,
       51918.85104957, 51946.87830017, 50662.408157  ])

In [65]:
result = pd.DataFrame()
result.index = test_data['id']
result['price'] = result_of_test
result

price
id                
1     57963.976018
2     52527.673481
3     45657.336702
4      6841.793840
5      6466.331586
...            ...
4996  55378.559842
4997  -1739.223131
4998  51918.851050
4999  51946.878300
5000  50662.408157

[5000 rows x 1 columns]

In [66]:
result.to_csv("sub5.csv")